/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SoutenirRouteImport } from './routes/soutenir'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as QuiSommesNousRouteImport } from './routes/qui-sommes-nous'
import { Route as ProjetRouteImport } from './routes/projet'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'

const SoutenirRoute = SoutenirRouteImport.update({
  id: '/soutenir',
  path: '/soutenir',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const QuiSommesNousRoute = QuiSommesNousRouteImport.update({
  id: '/qui-sommes-nous',
  path: '/qui-sommes-nous',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetRoute = ProjetRouteImport.update({
  id: '/projet',
  path: '/projet',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/impact': typeof ImpactRoute
  '/projet': typeof ProjetRoute
  '/qui-sommes-nous': typeof QuiSommesNousRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/soutenir': typeof SoutenirRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/impact': typeof ImpactRoute
  '/projet': typeof ProjetRoute
  '/qui-sommes-nous': typeof QuiSommesNousRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/soutenir': typeof SoutenirRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/impact': typeof ImpactRoute
  '/projet': typeof ProjetRoute
  '/qui-sommes-nous': typeof QuiSommesNousRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/soutenir': typeof SoutenirRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/impact'
    | '/projet'
    | '/qui-sommes-nous'
    | '/sitemap.xml'
    | '/soutenir'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/impact'
    | '/projet'
    | '/qui-sommes-nous'
    | '/sitemap.xml'
    | '/soutenir'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/impact'
    | '/projet'
    | '/qui-sommes-nous'
    | '/sitemap.xml'
    | '/soutenir'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  ImpactRoute: typeof ImpactRoute
  ProjetRoute: typeof ProjetRoute
  QuiSommesNousRoute: typeof QuiSommesNousRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SoutenirRoute: typeof SoutenirRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/soutenir': {
      id: '/soutenir'
      path: '/soutenir'
      fullPath: '/soutenir'
      preLoaderRoute: typeof SoutenirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qui-sommes-nous': {
      id: '/qui-sommes-nous'
      path: '/qui-sommes-nous'
      fullPath: '/qui-sommes-nous'
      preLoaderRoute: typeof QuiSommesNousRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projet': {
      id: '/projet'
      path: '/projet'
      fullPath: '/projet'
      preLoaderRoute: typeof ProjetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  ImpactRoute: ImpactRoute,
  ProjetRoute: ProjetRoute,
  QuiSommesNousRoute: QuiSommesNousRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SoutenirRoute: SoutenirRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
